### ISSUE TITLE
Free text rights statements in dpla:SourceResource dc:rights

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#1]
Free-text rights statements are not currently mapping to dpla:SourceResource dc:rights.
See the following OAI urls for examples:

CWU 
http://digitalcommons.cwu.edu/do/oai/?verb=ListRecords&set=publication:frederick_krueger&metadataPrefix=simple-dublin-core

EWU
http://cdm16794.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=EWUfreeman

**Comment by ewg118** [comment]
Done.
