### ISSUE TITLE
Trailing periods in dc:creator, dc:contributor, and dc:subject

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#10]
The Alliance Dublin Core Best Practices, the crosswalk, and harvester specs all state that the harvester will remove trailing punctuation from the creator, contributor, and subject fields. Unfortunately, we didn't consider the necessary presence of periods in cases like the following:

<dc:subject>Clinton, Jack W., D.M.D.</dc:subject>
<dc:contributor>Edwards, M.B.</dc:contributor>
<dc:creator>Hicks, Kiley A.</dc:creator>

Jodi and I would like to revise the transformations for these fields. We would like the harvester to remove all trailing punctuation from subjects, contributors, and creators **except** for periods. The periods, we'd like to keep.

**Comment by ewg118** [comment]
I have seen trailing periods on places and subjects, though. If we are looking to ignore trailing periods for initials, we can do a regular expression match to ignore anything ending with a capital letter and a period.

**Comment by adehner** [comment]
Good point! Thanks for thinking of and suggesting this. I think this is a good solution for most cases. But there will be abbreviations this reg ex won't catch. Jr., Lt., Gen., Col., Hon., to name a few.

@jalllibunn

**Comment by ewg118** [comment]
This one's done, although I have only I have only re-harvested one or two sets, so I am not sure the changes are visible yet.
