### ISSUE TITLE
Submission issues with Digital Commons

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#100]
@ewg118 
Institutions trying to contribute sets from Digital Commons instances are having trouble doing so. The problems may or may not be related. 

**Concordia:** Trying to re-contribute the set http://commons.cu-portland.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:campus/. She cannot contribute the set and gets the error "No metadata for setSpec publication:campus/".

I can contribute the set with my admin login AND her login by deleting it first. But she can't make that same process work. She has cleared her cache and switched browsers to no avail. 

I note that there are two setSpecs in this set: 
<setSpec>publication:campus</setSpec>
<setSpec>publication:cuarchives</setSpec>

**Central WA:** This one is urgent since the staff member is only in today. He's trying to contribute a set for the first time. 
https://digitalcommons.cwu.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:cwu_buildings/ 
He gets the error message 
![image](https://user-images.githubusercontent.com/25933545/41876683-d7e65d28-788b-11e8-9801-56a5da91a7aa.png)

I get the same error message and can't contribute the set. 

This one also has two setSpecs:
<setSpec>publication:cwu_buildings</setSpec>
<setSpec>publication:cwu_archives_special_collections</setSpec>

**Comment by ewg118** [comment]
Looks like a trailing forward slash in the set

**Comment by jallibunn** [comment]
@ewg118 
Indeed it seems to be, at least for Concordia. 

For CWU, I am trying to contribute the set without success. The harvester is churning along for a very long time without anything happening.

**Comment by jallibunn** [comment]
@ewg118 
Concordia now gets a new error when they try to enrich creators: 

"When I get to the enriching data options, and I choose Concordia University (Portland, Or.) to replace Concordia University – Portland as the creator (which is the main reason I’m recontributing this set in the first place), I get the error:
 SPARQL update failed.
I can still move forward to preview the records, but it shows the creator as Concordia University – Portland"

I was able to replicate this error on my admin account.

**Comment by ewg118** [comment]
I removed the trailing slash on the Central Washington and Concordia sets, and I was able to move into the validation screen successfully.

I found that the error you are getting when trying to remediate types or agents are related to a minor namespace glitch that arises in the upgrade between the older and newer version of Orbeon. I have successfully testing the publication of Concordia onto my own computer by normalizing Concordia University to the VIAF URI

**Comment by jallibunn** [comment]
@ewg118 , thanks for the update.

Can you clarify what is the next step in resolving this? Is the Orbeon issue something that you can address?

**Comment by ewg118** [comment]
It is already fixed.

**Comment by jallibunn** [comment]
@ewg118 OK, great!

**Comment by jallibunn** [comment]
@ewg118 , there is another set that is kicking off the "unable to parse the OAI-PMH response for ListSets. I've been able to replicate the problem several times. 

This one is from Western Oregon University. 
https://digitalcommons.wou.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:thenorm

The set appears well formed; is there something you see that I am missing? The only thing I am suspicious of is that it has multiple listSets properties.

**Comment by ewg118** [comment]
This is another sysadmin problem. 

curl -I https://digitalcommons.wou.edu/do/oai/?verb=ListSets
HTTP/1.1 404 Not Found
Server: nginx/1.2.1
Date: Wed, 27 Jun 2018 13:18:45 GMT
Content-Type: text/html; charset=UTF-8
X-Runtime: 0.208531

If you try to request the headers, you get a 404 Not Found instead of a successful HTTP request.

**Comment by jallibunn** [comment]
@ewg118 , thank you! I'll have them file an issue with BePress.
