### ISSUE TITLE
dc:isPartOf in test Primo OAI

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#11]
In the [test Primo OAI](http://harvester-dev.orbiscascade.org/oai-pmh/?verb=ListRecords&set=primo&metadataPrefix=oai_dc), dc:isPartOf contains an OAI request to list records in the record's native set. 

For example: 
<dc:isPartOf>
http://pdxscholar.library.pdx.edu/do/oai/?verb=ListRecords&set=publication:usp_grad&metadataPrefix=oai_dc
</dc:isPartOf>

According to the DC to Primo PNX crosswalk, dc:isPartOf should contain the Collection name (the OAI set name) as a text string, instead of the OAI request. See screenshot below for crosswalk:

<img width="988" alt="screen shot 2017-02-22 at 9 57 33 am" src="https://cloud.githubusercontent.com/assets/6174191/23225145/b7d10d66-f8e5-11e6-9888-880f771ee6de.png">

@jallibunn

**Comment by ewg118** [comment]
The underlying SPARQL query has been updated to grab the dcterms:title from the dcmitype:Collection.
