### ISSUE TITLE
datestamp argument in primo & primo-test OAI sets

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#12]
Please enable the addition of datestamp arguments ("from" and "until") to OAI requests for the primo and primo-test sets.

more info...
Primo begins by querying:
[http://harvester-dev.orbiscascade.org/oai-pmh/?verb=Identify](http://harvester-dev.orbiscascade.org/oai-pmh/?verb=Identify)

And then Primo adds a required date range to the OAI request. After adding the date range (see OAI below), the OAI was rejected and we got a 404. See the link below for an example.

[http://harvester-dev.orbiscascade.org/oai-pmh/?verb=ListRecords&metadataPrefix=oai_dc&set=primo-test&from=2014-03-01T21:14:59Z&until=2017-03-03T21:21:25Z](http://harvester-dev.orbiscascade.org/oai-pmh/?verb=ListRecords&metadataPrefix=oai_dc&set=primo-test&from=2014-03-01T21:14:59Z&until=2017-03-03T21:21:25Z)

@jallibunn

**Comment by ewg118** [comment]
This has been activated: http://harvester-dev.orbiscascade.org/oai-pmh/?verb=ListRecords&set=primo&metadataPrefix=oai_dc&from=2017-03-10&until=2017-03-11. You can use just from, just until, and both of them together for a range. Note that the arguments take xsd:date, not xsd:dateTime, as per the granularity specified by the Identify verb in the OAI-PMH feed. If Primo is limited to only operate with timestamps, this can be done pretty easily. The full timestamps are stored in the ore:Aggregation.

**Comment by ewg118** [comment]
Also of note, I activated GetRecord: http://harvester-dev.orbiscascade.org/oai-pmh/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:harvester-dev.orbiscascade.org:2c30a503e22e927fece336660fdfd505
