### ISSUE TITLE
Replace hyphen with a forward slash in date ranges

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#13]
Currently the hyphen, separating 2 dates in a date range, is not replaced with a forward slash. This can be seen in date fields for DPLA (SourceResource dcterms:date) and those for Primo (OAI dc:date).

Sets for testing:
- http://oregondigital.org/oai?verb=ListRecords&metadataPrefix=oai_qdc&set=oregondigital:lee-moorhouse
- http://cdm16472.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=p16472coll3

According to the crosswalks to DPLA and Primo, the hyphens should be replaced with a forward slash
DPLA crosswalk:
<img width="1113" alt="screen shot 2017-03-10 at 1 29 16 pm" src="https://cloud.githubusercontent.com/assets/6174191/23813943/1dcdcd36-0596-11e7-8146-cd4e353033bb.png">

Primo crosswalk:
<img width="822" alt="screen shot 2017-03-10 at 1 32 30 pm" src="https://cloud.githubusercontent.com/assets/6174191/23813954/2b9863fe-0596-11e7-9717-9e58915f3a35.png">

@jallibunn

**Comment by ewg118** [comment]
Fixed. I re-harvested the ORPU set, and you should see the changes in the RDF and OAI-PMH for Primo. E.g.
    `<dc:date>1942/1957</dc:date>`
  `<dc:date.start>19420101</dc:date.start>`
    `<dc:date.end>19571231</dc:date.end>`

The dates in RDF are not a literal "1942/1957". They are modeled into edm:TimeSpan with edm:begin and edm:end.

**Comment by adehner** [comment]
Thanks Ethan!
