### ISSUE TITLE
ExLibris Institution codes in dc:publisher

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#14]
I finally added the ExLibris institution codes to this repository table:
https://docs.google.com/spreadsheets/d/1Omw-7Avf5n2u8d-dZa_dgqXeGvVNVjRLTJ0NzNdtoTE/edit?usp=sharing

Per the Primo crosswalk, please populate the dc:publisher field (destined for Primo) with only the ExLibris institution code (the screenshot below and crosswalk are both incorrect in referencing the OCLC code. this was my mistake. they should say that the harvester transforms the institution's marc code to the ExLibris institution code.)
<img width="823" alt="screen shot 2017-03-10 at 1 53 29 pm" src="https://cloud.githubusercontent.com/assets/6174191/23814675/44af9440-0599-11e7-9bfc-be592cd7ea52.png">

@jallibunn

**Comment by ewg118** [comment]
I thought that the OAI-PMH for Primo would include the formal institution name as the dc:publisher, not the code. Does the Primo pipe read the ExLibris code and convert that into a human-readable label?

**Comment by adehner** [comment]
Yes. There is already a mapping table set up in Primo to do this conversion for data piped in from Alma. Using the code in dc:publisher will allow us to use this mapping table for human-readable display. But more importantly, using the code will allow us to set up institutional sub-scopes in Primo. And the institutional sub-scopes will enable more flexible configuration for Alliance institutions.

**Comment by ewg118** [comment]
A MARC-Ex Libris concordance has been added into the Harvester config file, so the publisher URI will get converted into the Ex Libris code in the Primo OAI-PMH. You can see an example here: http://harvester-dev.orbiscascade.org/oai-pmh/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:harvester-dev.orbiscascade.org:2c30a503e22e927fece336660fdfd505
