### ISSUE TITLE
dcterms:date is absent in validation results (Digital Commons & Dspace)

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#15]
In the beta interface, I'm not seeing dcterms:date in OAI-PMH validation results for records from Digital Commons and Dspace sets.

A few example sets:
waeic
http://digitalcommons.cwu.edu/do/oai/?verb=ListRecords&set=publication:kaviani&metadataPrefix=simple-dublin-core

wachene
http://dc.ewu.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:biol_fac

orgnf
http://digitalcommons.georgefox.edu/do/oai/?verb=ListRecords&set=publication:the_academician&metadataPrefix=simple-dublin-core
http://digitalcommons.georgefox.edu/do/oai/?verb=ListRecords&set=publication:audio_fourflats&metadataPrefix=simple-dublin-core

wau
http://digital.lib.washington.edu/dspace-oai/request?verb=ListRecords&set=col_1773_4972&metadataPrefix=oai_dc

@jallibunn

**Comment by ewg118** [comment]
When fixing issue 13 on years separated by hyphen, I broke some date parsing, so I tightened the regular expressions. So this is resolved.

**Comment by adehner** [comment]
Thanks!
