### ISSUE TITLE
dcterms:rights values are trimmed at semicolon

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#16]
In the beta harvester validation results, dcterms:rights values are truncated when a semicolon is present. All text following the semicolon is removed. Free-text rights statements are repeatable; and like free-text descriptions, they may contain semicolons. 

Please update the harvester's parsing code to allow the presence of semicolons in dcterms:rights and to harvest dcterms:rights values in their entirety.

An example set:
waeic
http://digitalcommons.cwu.edu/do/oai/?verb=ListRecords&set=publication:kaviani&metadataPrefix=simple-dublin-core

@jallibunn

**Comment by ewg118** [comment]
Okay, the dc:rights template no longer splits on ';'.

**Comment by adehner** [comment]
Thanks!
