### ISSUE TITLE
Error message: When a set does not validate

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#17]
The following set does not validate, but there is no error message or indicator communicating what went wrong. Can you create such a message in the browser, indicating how to proceed when this happens.

orfp
http://commons.pacificu.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:hip

**Comment by ewg118** [comment]
Okay. I'll look into the error reporting, but it does look like there's no
URI in the OAI PMH

**Comment by adehner** [comment]
Ah, I see that now that I look at the OAI PMH. Thanks. Hopefully folks won't actually submit sets without URIs. But in case it does happen, an error message would be helpful.

**Comment by ewg118** [comment]
I found the glitch in the code that resulting in the error reporting not functioning correctly. Thanks for finding a set that had errors that I was able to use for testing--I haven't encountered sets with other such errors. You can test this yourself in the admin panel. Note that the "download CSV" button isn't working yet to download a full report, but the first 20 errors will display on the validation results page.
