### ISSUE TITLE
Error message: When the sourceResource, oreAggregation, and webResource are absent

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#18]
When viewing the following set in the beta interface validation results...
the sourceResource, oreAggregation, and webResource are absent when a record's info icon is clicked.
However the record title and URI are present.

When this happens, it would be helpful to see an error message in the browser to communicate how to proceed.

oru
http://oregondigital.org/oai?verb=ListRecords&metadataPrefix=oai_dc&set=oregondigital:lee-moorhouse

**Comment by ewg118** [comment]
I improved ajax error handling for failed attempts to display the results (from a GetRecord call). This is a result of Oregon Digital erroring, and not inherent to a bug in the harvester itself. See http://oregondigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oregondigital.org:lee-moorhouse/df66wk80p

**Comment by adehner** [comment]
Thank you, and thanks for explaining.

Anneliese
