### ISSUE TITLE
Place normalization

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#19]
The beta harvester interface offers normalization of places (geonames). Due to the variety in local practices, the Alliance decided against recommending the use of any controlled vocabulary for spatial metadata. 

Please remove this feature. Or comment it out, if you like, in case the consortium agrees to do this in the future.

**Comment by ewg118** [comment]
It's been commented out, but can be activated later. Bear in mind that the normalization of places applies to the place names from textual labels--not specific latitudes and longitudes. You might find that the place name facet in Primo contains wide variation in labels for the same place.

**Comment by adehner** [comment]
Thanks Ethan.

You are correct about place name facets in Primo. At this point, place
names will only be keyword searchable in Primo. With such variety in
values, facets wouldn't be useful. If the Alliance pursues place name
faceting, some kind of normalization will definitely need to happen.

Anneliese

**Comment by adehner** [comment]
We're still seeing geonames URIs in the beta harvester validation results and in the Primo OAI. Perhaps the geonames lookup list is still present for a few sets?
WSU's Matsura set is an example that shows this.

@jallibunn

**Comment by ewg118** [comment]
The Geonames normalization has been disabled in the OAI-PMH to RDF XSLT. The Matsura set will need to be re-harvested.
