### ISSUE TITLE
HTML tags in dpla:SourceResource dcterms:description

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#2]
HTML tags are present in dpla:SourceResource dcterms:description, but they should be stripped from description values. See the following OAI url:

EWU
http://dc.ewu.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:biol_fac

**Comment by ewg118** [comment]
The HTML tags (and duplicate whitespace) should be stripped from every textual element now.

	<xsl:function name="harvester:cleanText">
		<xsl:param name="val"/>
		
		<xsl:variable name="html-stripped" select="replace(replace($val, '&lt;[^&gt;]+&gt;', ' '), '\\s+', ' ')"/>
		
		<xsl:choose>
			<xsl:when test="substring($html-stripped, string-length($html-stripped), 1) = '.'">
				<xsl:value-of select="substring($html-stripped, 1, string-length($html-stripped) - 1)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$html-stripped"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:function>

Let me know if you still see some. It's possible I haven't called the cleanText() function every possible place.

**Comment by adehner** [comment]
One of our beta testers just pointed out some of that duplicate whitespace. 

It's visible in the description field of http://digitalcommons.linfield.edu/dory_archphotos_all/15. See screenshot below (the spaces are present where <em></em> was removed around the words "Mox Nix" and "Dungie"):
<img width="416" alt="screen shot 2017-04-12 at 9 21 00 am" src="https://cloud.githubusercontent.com/assets/6174191/24968277/a3450be8-1f61-11e7-819d-83a3e5d02d85.png">

@jallibunn
