### ISSUE TITLE
Agent normalization: SNAC

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#20]
The beta harvester interface offers normalization of agents (viaf or snac). 

For creators/contributors, the Alliance Dublin Core Best Practices (and harvester specs) recommend using the controlled vocabularies of VIAF members (LCNAF, ULAN, ISNI, etc.) But the Alliance Best Practices (and harvester specs) do not mention SNAC. Please remove SNAC from the harvester's agent normalization.

**Comment by ewg118** [comment]
SNAC has been commented out, but it can be re-enabled later if you decide to use it (especially for families, which are absent from VIAF)

**Comment by adehner** [comment]
Thanks Ethan!
