### ISSUE TITLE
dc:creator and dc:creator.undated in OAI for Primo

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#22]
For creator values in the Primo OAI:

Currently normalized creator values are present in dc:creator as URIs. Creator values should be present in dc:creator as a text string because Primo doesn't know what to do with URIs. This goes for dc:contributor as well.

When a dc:creator value contains birth/death dates, the qualified field dc:creator.undated should be present as well. The qualified field should contain the creator value without dates, per the harvester specs. This goes for dc:contributor and dc:contributor.undated as well.

<img width="653" alt="screen shot 2017-03-16 at 1 24 50 pm" src="https://cloud.githubusercontent.com/assets/6174191/24017213/500d717e-0a4c-11e7-84ca-1279297cfda4.png">

Example set:
waps
http://content.libraries.wsu.edu/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=matsura

**Comment by ewg118** [comment]
Okay, resolved.
