### ISSUE TITLE
Data provider URI

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#23]
Currently the data provider URI points to Archives West repository information.

When meeting in January ([Jodi's notes](https://docs.google.com/a/orbiscascade.org/document/d/1fDLPLzs3CXm9_veOf85FeMgpu2Z-CFiln0iMJhjRA28/edit?usp=sharing)) we decided that linking to the Archives West repository page doesn't make sense for non-Archives West users who won't have an equivalent place to link to.

How will the data provider uri be handled for non-Archives West users?

@jallibunn

**Comment by ewg118** [comment]
It won't be ready by the 24th, but the harvester config will be updated so that partners are flagged as being part of Archives West or not. If not, then they'll have a different URI pattern within the harvester, e.g., harvester.orbiscascade.org/agency/wasu

**Comment by ewg118** [comment]
This has been resolved.
