### ISSUE TITLE
Info icon ("i" in a circle) in validation results

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#24]
In the beta harvester interface, the user clicks an info icon (represented by an "i" in a circle) to toggle record visibility.

Please replace this icon with a larger icon that traditionally communicates accordion/toggle/ functionality (eg. plus ("+") and minus ("-") signs OR downward/upward facing triangles)

@jallibunn

**Comment by ewg118** [comment]
Done.
