### ISSUE TITLE
Add link to 'start over' or 'enter a new set'

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#26]
When a user is in the process of adding a set (editing, enriching, previewing) he/she may wish to start over, enter a new set, or visit the 'setup options' page. Please add a link to enable this navigation. There are several ways this could be done, here are a couple...

- If the user is viewing the the EDITING, ENRICHING, PREVIEW SET, or CONTRIBUTE SET page, replace the text of the "SET UP OPTIONS" tab with "START OVER" or "ENTER A NEW SET" and make the tab clickable.

- Add a "start over" or "enter a new set" link somewhere else on the page. Perhaps at the beginning of the breadcrumb navigation. Or if it would make more logical sense, add it somewhere else.

@jallibunn

**Comment by ewg118** [comment]
Okay, when the user has moved past the setup options page, the button is replaced with "Start Over". Clicking "Start Over" launches a dialog that prompts the user to click "Yes" to start over from the beginning. There's also an "Import a new set" button on the very last page of the interface, after having contributed a set.

**Comment by adehner** [comment]
Nice. I like the little 'start over' icon too.
