### ISSUE TITLE
Add ">" between breadcrumb navigation items

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#27]
Add delimiters between breadcrumb navigation items to communicate that this is a progression rather than standalone pages.

SETUP OPTIONS  >  EDITING  >  ENRICHING  >  PREVIEW SET  >  CONTRIBUTE SET

Here is the image that the Alliance uses to delimit breadcrumbs throughout its website. Using this image would be ideal, but &gt would be okay too:
https://www.orbiscascade.org/img/anchor-arrow-gray.png

@jallibunn

**Comment by ewg118** [comment]
Added the chevron-right bootstrap glyph to each breadcrumb

**Comment by adehner** [comment]
Looks great. Thanks!
