### ISSUE TITLE
Develop functionality to preview QDC records before "contributing"

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#28]
Please develop functionality to allow a user to preview QDC records before contributing them to Primo. If the user selects 'Primo only' or 'DPLA and Primo' in the 'setup options' page, then present QDC records (as html) in the 'preview set' page.

If the user selects 'DPLA and Primo' in the 'setup options' page, then the present both QDC and RDF records (as html) in the 'preview set' page. This can be a tabbed layout (one tab for 'Primo', one tab for 'DPLA') or another layout that is easily toggled.

@jallibunn

**Comment by ewg118** [comment]
Okay, this is finished, and has been applied to the test page as well (there is a drop down menu on the test page to select "Primo" as the Model, as opposed to the "DPLA MAP" default. It functions on GetRecord (in the admin panel) and ListRecords (the whole set or test of 10 records).

It's basically a pipeline that layers a sequence of transforms: original OAI-PMH -> DPLA MAP RDF -> OAI Dublin Core -> HTML. Note that unlike the actual Primo response generated from the SPARQL endpoint, the creators, AAT terms, and Collection name will not be normalized into their title/skos:prefLabel. They stay as an URI, if there's a lookup already constructed.

**Comment by adehner** [comment]
This is exciting, but I'm not seeing the drop down menu to select "Primo" as the model. Perhaps I'm looking in the wrong place. Where can I see it?

**Comment by ewg118** [comment]
http://harvester-dev.orbiscascade.org/test

As for viewing the records on the validation page: If "Primo" is set as the target in the first page of the import process, then it will display the Primo Dublin Core when expanding the record on the validation page. If "DPLA" or "Both" are selected, it will display the DPLA MAP RDF.
