### ISSUE TITLE
Digital Commons dates: YYYY-01-01Thh:mm:ssTZD

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#3]
Digital Commons specifies month and day values for all dates, regardless of the date entered by the cataloger. If the cataloger enters a year value (YYYY), Digital Commons will output the date as January 1 of the cataloged year (YYYY-01-01). In these cases, the output date is inaccurate. 

To correct for this, we have requested that the month and day values be stripped from Digital Commons dates when the month=01 AND the day=01. In these cases, only the year YYYY should be present after the harvester's transformations.

**Comment by adehner** [comment]
Forgot the example urls:

CWU
http://digitalcommons.cwu.edu/do/oai/?verb=ListRecords&set=publication:frederick_krueger&metadataPrefix=simple-dublin-core

Concordia
http://commons.cu-portland.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:campus

**Comment by ewg118** [comment]
Should be resolved.
