### ISSUE TITLE
Add validation of date, type, and rights to validator

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#30]
Currently the beta harvester validates on the presence of title and identifier. Please also validate on the presence of date, type, and rights.

When type and/or rights are absent the process should not be halted as the user may choose to globally edit type and/or rights. Instead of halting, present the user with a message indicating that x number of records lack type and/or x number of records lack rights.

@jallibunn

**Comment by ewg118** [comment]
DCMI Types, Rights statements, and Dates will now display. There will be a validation error for records that do not have a dc:date, and the repository will have to fix these records. Let me know if you want the date validation disabled. Date is not required in the DPLA MAP

**Comment by adehner** [comment]
When testing the WSU set that lacks date in 6 records (http://content.libraries.wsu.edu/oai/oai.php?verb=ListRecords&set=cchm&metadataPrefix=oai_dc), I didn't see a validation error and the harvest/contribution was not halted. Where should I see the validation error?

**Comment by ewg118** [comment]
I commented it out until you could confirm that's what you wanted.

**Comment by adehner** [comment]
Gotcha. I asked Jodi to send confirmation.

**Comment by ewg118** [comment]
There is something broken about the error reporting on the harvester-dev, and I don't have time to troubleshoot. The Orbeon version is different on the server than my laptop, so this makes it difficult to track down the problem. I may have to restore the harvester code from an earlier version on Github. I have tested on the smaller waps set, where the error is occurring, but it seems to be functioning for other sets.

**Comment by adehner** [comment]
I'm not seeing validation errors when date is absent.
I used this set to test: http://cdm16794.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=EWUfreeman

**Comment by ewg118** [comment]
I fixed the glitch I introduced the other day when attempting to get the DCMI Type / Mime type drop downs to override validation errors.
