### ISSUE TITLE
Replace "Archives West" with Orbis Cascade branding in header

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#31]
Please remove "Archives West" from the header of all pages.

Currently visible on the page below and possibly others:
https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/

Instead, please add the Orbis Cascade Alliance logo (below) along with the word "HARVESTER" in the header of all pages.

![orbiscascade](https://cloud.githubusercontent.com/assets/6174191/24429898/e641f572-13c8-11e7-9979-f496e4c12c42.jpg)

@jallibunn

**Comment by ewg118** [comment]
Okay, done.

**Comment by adehner** [comment]
I'm not seeing this change on the following pages (cleared my cache too). Where has this been changed?

https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/import
https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/

**Comment by ewg118** [comment]
The changes have not been pulled to the server. They cannot be pulled to
the server until Curtis updates the credentials to allow me to log in from
my laptop

**Comment by jallibunn** [comment]
Hi, this looks good. I'd like the logo scaled down in size a bit--see the
default size on the https://www.orbiscascade.org/ site. Anneliese, if
there's a way to translate that into more precise numbers please jump in.

Thanks, Ethan, for all of this good work. Much appreciated.

Best, Jodi
