### ISSUE TITLE
Replace "optional" with "required" in the standardized rights statement "hint"

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#32]
In the 'Editing' page, please replace 'optional' with 'required' in the standardized rights statement hint that displays in a yellow box. See screen shot below:

<img width="540" alt="screen shot 2017-03-28 at 3 18 45 pm" src="https://cloud.githubusercontent.com/assets/6174191/24430324/dc062a0e-13ca-11e7-8c04-ef0209423455.png">

@jallibunn

**Comment by ewg118** [comment]
Done.
