### ISSUE TITLE
Replace "textual" with "free-text" in the free-text rights statement "hint"

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#33]
In the 'Editing' page, please replace 'textual' with 'free-text' in the free-text rights statement hint that displays in a yellow box. See screen shot below:

<img width="462" alt="screen shot 2017-03-28 at 3 27 24 pm" src="https://cloud.githubusercontent.com/assets/6174191/24430424/6fb3081c-13cb-11e7-9a3f-cf49840ea7d2.png">

@jallibunn

**Comment by ewg118** [comment]
Done.
