### ISSUE TITLE
VIAF & AAT URIs in Primo OAI

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#34]
We're seeing VIAF and AAT URIs in the Primo OAI.
Because Primo can't do anything with the URIs, the creator/contributor/genre values for Primo should be text strings.

@jallibunn

**Comment by ewg118** [comment]
All sets that would normalize to VIAF and AAT URIs should be re-harvested. The generation of skos:Concept and edm:Agent data objects was only implemented in the days before I left for Oxford.

**Comment by ewg118** [comment]
Now that the skos:prefLabel issue has been sorted out, this is functional. I found a glitch in my code that was preventing the creation of the edm:Agent RDF on harvest. The SPARQL query for the Primo OAI-PMH has been extended to include the triples for dcterms:creator and dcterms:contributor. The preferred label will now display in the Dublin Core. I re-harvested the Matsura collection, so you can see it at http://harvester-dev.orbiscascade.org/oai-pmh/?verb=ListRecords&set=primo&metadataPrefix=oai_dc
