### ISSUE TITLE
Empty dc:publisher in Primo OAI

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#35]
In Primo testing, we discovered that dc:publisher is empty in some records of the primo OAI set.

I'm seeing this in WWU, UW, and Linfield sets. These repositories are not part of Archives West, so their data provider base url is http://harvester.orbiscascade.org/agency/. Perhaps the OAI generating code just needs to account for this base url in addition to http://archiveswest.orbiscascade.org/contact# ?

@jallibunn

**Comment by ewg118** [comment]
Yeah, that's exactly it. I hadn't updated the code to parse the MARC code out of the agency URI to derive the Ex Libris code. I have updated the code, so it should work now, but I don't actually have the data on my laptop to test it.

**Comment by adehner** [comment]
Thanks! I'm seeing the ExLibris codes in the OAI now.
