### ISSUE TITLE
HTML tags in dpla:SourceResource dcterms:title

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#36]
HTML tags are present in dpla:SourceResource dcterms:title, but they should be stripped from title values. See the following OAI url:

Linfield
http://digitalcommons.linfield.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:dory_archphotos

@jallibunn

**Comment by ewg118** [comment]
HTML tags are now stripped from the dc:title

**Comment by adehner** [comment]
I'm still seeing them when I step through the contribution process and preview the Linfield set: http://digitalcommons.linfield.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:dory_archphotos

<img width="540" alt="screen shot 2017-04-13 at 3 03 58 pm" src="https://cloud.githubusercontent.com/assets/6174191/25026267/9969a8a0-205a-11e7-92a3-8a3e87d4d06e.png">

However I do see that they have been removed from dcterms:title in the SourceResource
<img width="356" alt="screen shot 2017-04-13 at 3 05 32 pm" src="https://cloud.githubusercontent.com/assets/6174191/25026287/ab8b5484-205a-11e7-8993-4a0f08ee4286.png">

**Comment by ewg118** [comment]
Okay, the code in the validation phase of the import web interface has been updated to strip HTML tags from title and the genre/agent names
