### ISSUE TITLE
Preview: Paging through records is not working as expected

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#38]
Clicking the left-pointing arrows (to view previous page of records) does not return the correct number of records.

See sequence of screenshots below for previewing this set: http://digitalcommons.linfield.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:dory_archphotos

1st page of record preview. Note the number of records, 1-50:
<img width="964" alt="screen shot 2017-04-14 at 3 54 03 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058128/37b0a2c2-212b-11e7-97ab-1d4d3a5c28b4.png">

2nd page of record preview (after clicking the right-pointing navigation arrows):
<img width="961" alt="screen shot 2017-04-14 at 3 54 16 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058135/42e2852a-212b-11e7-9830-c9af9fb3bce9.png">

1st page of record preview (after clicking the left-pointing navigation arrows) Here you will see only records 1-13 instead of 1-50:
<img width="969" alt="screen shot 2017-04-14 at 3 54 30 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058156/60696e1a-212b-11e7-85b2-a7390a48763a.png">

@jallibunn

**Comment by ewg118** [comment]
Math glitch on the upper limit for the back button. Fixed now.
