### ISSUE TITLE
Preview/Error: Records do not display for monw Omeka set

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#39]
Clicking a downward pointing arrow does not display a record for the following set: http://omeka.wou.edu:8080/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=2

The toggle icon for the record in the screenshot below has been clicked:
<img width="739" alt="screen shot 2017-04-14 at 4 04 34 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058287/9d9bfefa-212c-11e7-8fee-170818cb03a5.png">

@jallibunn

**Comment by ewg118** [comment]
GetRecord seems to be broken: http://omeka.wou.edu:8080/oai-pmh-repository/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:omeka.wou.edu:8080:33

**Comment by ewg118** [comment]
I'm going to close this since it seems to have been reported to the institution.
