### ISSUE TITLE
De-dupe language values

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#40]
After transforming language names to 639-2 codes, please de-dupe language values in a single record. 

See harvester specs:
<img width="631" alt="screen shot 2017-04-14 at 4 11 39 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058337/291a3276-212d-11e7-9049-bb5797e2f032.png">

Duplicate language values can be seen in the following sets:
http://content.wwu.edu/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=walc 
http://cedar.wwu.edu/do/oai/?verb=ListRecords&set=publication:klipsun_magazine&metadataPrefix=simple-dublin-core

@jallibunn

**Comment by ewg118** [comment]
Does it matter if there's no actual duplication once harvested (only in the
preview)?

**Comment by adehner** [comment]
Yes, the preview should be as accurate as possible.

**Comment by ewg118** [comment]
Okay, I have changed the code so that all possible language values (in multiple dc:language elements and multiple labels separated by ; in one or more elements) normalized first, and then duplicates weeded out before generating unique dcterms:language values.
