### ISSUE TITLE
HTML tags are present when enriching creator values

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#42]
HTML tags are removed before record preview, but they are present when enriching creator values. Enrichment would be smoother if html tags were removed beforehand.

This is visible when enriching creator/contributors from the following set:
http://cdm16786.contentdm.oclc.org//oai/oai.php?verb=ListRecords&set=maps&metadataPrefix=oai_dc

<img width="665" alt="screen shot 2017-04-14 at 4 22 38 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058525/2f08b93a-212f-11e7-8c1e-ae94d9417a87.png">

@jallibunn

**Comment by ewg118** [comment]
This issue is fixed, but this set needs to fix their data so they don't have multiple creators separated by HTML line break tags.

**Comment by adehner** [comment]
Thanks Ethan. Yes, hopefully they will fix these locally if they choose to contribute this set.
