### ISSUE TITLE
Preview: toggle record visibility, revisited

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#47]
In issue #24 we asked you to replace the info icon with "+" or "-" icons or downward/upward pointing arrows. Thank you for adding the downward/upward arrows. 

Unfortunately the Preview page continues to be confusing for Alliance users. To improve usability of the Preview page, we have 2 requests:

1. Please set the first record in the preview page to be open/expanded by default. 

2. Please replace the current arrows with the following.
- When a record is closed/collapsed, place a rightward pointing arrow to the left of the record
- When a record is open/expanded, place a downward pointing arrow to the left of the record

@jallibunn

**Comment by ewg118** [comment]
I have changed the triangles, but no. 1 doesn't seem to be possible. The GetRecord mechanism is an ajax call on a button click, but the call can't be made because the HTML div container element for the GetRecord hasn't actually been constructed in the DOM yet.

**Comment by ewg118** [comment]
I'm going to close this because any possible solution here strays pretty far into "hacked" territory and is more difficult to maintain through updates to the XForms engine

**Comment by adehner** [comment]
Sounds good to me.
