### ISSUE TITLE
Process each dc:title

### ISSUE THREAD

**Issue by ewg118** [Orbis-Cascade-Alliance/harvester#48]
dc:title[1] should be dcterms:title, all subsequent dcterms:alternative

**Comment by ewg118** [comment]
This should be fixed, but can you find a set to test?

**Comment by adehner** [comment]
Looks good! Thanks.

I tested these 2:
http://cdm16786.contentdm.oclc.org//oai/oai.php?verb=ListRecords&set=maps&metadataPrefix=oai_dc

http://cedar.wwu.edu/do/oai/?verb=ListRecords&set=publication:klipsun_magazine&metadataPrefix=simple-dublin-core

**Comment by adehner** [comment]
In Primo testing, I see that titles are still concatenated in the OAI output for Primo. Please make this change to QDC output for Primo as well.

map 1st title to dc:title
map subsequent titles to dcterms:alternative

**Comment by ewg118** [comment]
Data have to be re-harvested in order these changes to take effect

**Comment by adehner** [comment]
Okay, thanks!
