### ISSUE TITLE
Preview: Suppress ore:Aggregation, SourceResource header, and webResource headers

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#49]
In the preview page, please suppress the following from view:

The SourceResource header:
<img width="383" alt="screen shot 2017-04-17 at 4 14 27 pm" src="https://cloud.githubusercontent.com/assets/6174191/25108195/0286eab0-2389-11e7-8b9c-d8dba056fe0a.png">

The entire ore:Aggregation section:
<img width="862" alt="screen shot 2017-04-17 at 4 12 59 pm" src="https://cloud.githubusercontent.com/assets/6174191/25108156/c3dbc8da-2388-11e7-8f85-33edf5883cd8.png">

The webResource headers:
<img width="282" alt="screen shot 2017-04-17 at 4 15 42 pm" src="https://cloud.githubusercontent.com/assets/6174191/25108214/2a481632-2389-11e7-93d9-d1f962c894d1.png">

**Comment by ewg118** [comment]
Done.
