### ISSUE TITLE
dpla:SourceResource dcterms:description is present but empty

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#5]
When the thumbnail URL is stripped from dc:description, the dcterms:description property remains even though it is empty.
<img width="780" alt="screen shot 2017-02-14 at 10 58 00 am" src="https://cloud.githubusercontent.com/assets/6174191/22944231/da5772cc-f2a4-11e6-811e-2ce8bee5d891.png">

**Comment by ewg118** [comment]
I think this should be fixed, but I haven't tested it on this set. Conditional should have it sorted: `<xsl:if test="dc:description[not(matches(., '.jpe?g$'))]">`
