### ISSUE TITLE
Updates to the validation error page

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#50]
Please make the following changes to the validation error page:

1. Replace the page title "Preview your records and contribute this set" with "Your records are missing required data"

2. Below the page title, add the following text:
The records below are missing data required by the Alliance Dublin Core Best Practice Guidelines (DCBPG). This set cannot be contributed as is. Please go back and edit your records to be compliant with DCBPG. If you believe this analysis is a mistake, please contact Alliance staff (jodiab@orbiscascade.org).

3. Style each record's error by changing the text color to red or changing the error's background color to match the alert's background color.

4. Add a button/link to download the .csv error report

@jallibunn

**Comment by ewg118** [comment]
I've done 1, 2, and 3, but haven't fixed CSV yet.

**Comment by adehner** [comment]
Thanks for updating the title and text.
The red background is an improvement, it definitely looks like an error page now! But I think I was unclear in my request. 

Instead of adding the red background to the entire record like this:
<img width="953" alt="screen shot 2017-04-24 at 10 42 47 am" src="https://cloud.githubusercontent.com/assets/6174191/25350782/1bc40e0c-28db-11e7-87f6-8911aca548be.png">

Can you only add the red background to the error? So in this example, the red background would be added to this text only:
Error         No valid format (MIME type) detected.

**Comment by ewg118** [comment]
The error backgrounds have been updated to only highlight the error elements. I have commented out the CSV download bit because I haven't gotten it working yet. I can generate the CSV in the XForms engine, but the download part doesn't actually include the file.

**Comment by ewg118** [comment]
This finally works. The XForms mediatype and filename elements in the xxforms:download control needed to point to a @ref containing the filename and mime-type values for download, not simply just text value. 

Incorrect: `<xforms:mediatype>text/csv</xforms:mediatype>`
Correct: `<xforms:mediatype ref="instance('csv-download')/@mediatype"/>`
