### ISSUE TITLE
Add Reed College's MARC agency code

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#52]
Reed College's MARC agency code (orpr) is missing from the repository dropdown menu. Please add it.

@jallibunn

**Comment by ewg118** [comment]
According to the Harvester agency code spreadsheet, they will have a homegrown system, but it isn't activated yet. I added 'orpr' under the `<other>` heading for DAMS systems, but the OAI-PMH->RDF XSLT will have to be updated for a conditional statement to parse their thumbnail reference images later. So, currently, the harvester will only generate a dpla:SourceResource and ore:Aggregation, but no edm:WebResources.

**Comment by adehner** [comment]
Thanks!
The spreadsheet is accurate in this regard. I'll check with Jodi on their timeline for OAI activation.
