### ISSUE TITLE
Editing: add yellow hints for genre, format, and language

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#53]
In the harvester's editing page, please add yellow hints (text that appears on hover) for genre, format, and language. The text is below:

genre: The nature or genre of the resource.
format: The MIME type of the resource.
language: The language of the resource.

@jallibunn

**Comment by ewg118** [comment]
I added these hints, as well as a hint for hovering the mouse button over the AAT genre result list: "Click on a genre heading to read the genre's definition, below."
