### ISSUE TITLE
Standardized rights in dpla:SourceResource, ore:Aggregation, and edm:WebResource

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#55]
Please map a record's standardized rights statement to the following:

dpla:SourceResource dc:rights
ore:Aggregation edm:rights
edm:WebResource edm:rights (both thumb and reference)

@jallibunn

**Comment by ewg118** [comment]
The rights statements have been restored into ore:Aggregation and edm:WebResource. From what I can tell from the MAP, the rights can be a URI or text in the dpla:SourceResource, but a URI in the others.
