### ISSUE TITLE
Enriching creators/contributors: instructional language

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#56]
1.Please update the text to the left of the viaf lookup box from "Search" to "Search VIAF"
2. Please update the text in the lookup submit button from "Search" to "Search VIAF"
3. Please replace the text at the top of the creator/contributor enrichment page with the following language:

Your creators/contributors are listed below. 

If your creator/contributor values are listed with blue links, they automatically matched Library of Congress preferred labels in VIAF. Click a blue link to view the matched VIAF record. To dismiss a match, click the "x" icon to the right of the blue link.

If your creator/contributor values are listed with a VIAF search box, they do not match Library of Congress preferred labels in VIAF and cannot be enriched as is. To find a match and enrich a value:

- Select whether the value is a "Personal" or "Corporate" name.
- Type a variation of your creator/contributor value in the "Search VIAF" box and click the "Search VIAF" button. If potential matches are found, they will display as a list of names below the search box.
- Click a name from the list, and it will appear below the "Name" box.
- Click the blue icon, after the name, to review the name's VIAF authority record.
- If this is the VIAF record you want, click the "Select" button to match your creator/contributor value with the VIAF record. A blue VIAF URI will replace the VIAF search box when your value has been matched.

If no match is found in VIAF, then the original creator/contributor value from your set will be preserved in the DPLA and/or Primo output. 

@jallibunn

**Comment by ewg118** [comment]
Okay, done.
