### ISSUE TITLE
Creative Commons licenses

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#57]
For Rights Editing:
Please add all Creative Commons licenses to the options in the standardized rights dropdown menu.

@jallibunn

**Comment by ewg118** [comment]
I added these and tested that they come through in the RDF output. The label in the drop down menu begins with RS: for Rightsstatements.org and CC: for Creative Commons? Do you think this is obvious enough or do you think the drop-down menu needs to be preceded with a paragraph that defines these abbreviations?

I added the CC licenses into the test page.
