### ISSUE TITLE
Editing Rights: Text updates

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#58]
Please update the text for editing rights according to the screenshot and notes below:
<img width="548" alt="screen shot 2017-04-26 at 2 24 05 pm" src="https://cloud.githubusercontent.com/assets/6174191/25457983/fdb3316e-2a8c-11e7-854c-cf59574e940c.png">

Yellow hint for the standardized rights statement:
Required (if not already present in the set) standardized rights statement from RightsStatement.org or CreativeCommons.org

Yellow hint for the free-text rights statement:
Required (if not already present in the set) free-text rights statement, that augments and enhances the standardized rights statement

@jallibunn

**Comment by ewg118** [comment]
Done.
