### ISSUE TITLE
Permission agreement

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#59]
At the bottom of the Setup Options form/page, please add the text below. After the text, add a checkbox with the label "Agree". This checkbox must be checked to "Continue" in the contribution process.

Text:
I am acting on behalf of my institution to authorize the Orbis Cascade Alliance (Alliance) to harvest the metadata for the set specified in “Set URL” (above) for the purpose of sharing with the Digital Public Library of America (DPLA), under the terms of the agreement established between the DPLA and the Alliance. By doing so, I understand that the digital collections metadata -- but not the digital collections themselves -- will be made available under a Creative Commons Zero (CC0) Dedication [link text to https://creativecommons.org/publicdomain/zero/1.0/]. 

In addition to contributed metadata as authorized by institutions, image previews will also be available in the DPLA. Digital content associated with the metadata will not be moved or duplicated; rights for this content will not be affected by the availability of the metadata or previews in the DPLA.

@jallibunn

**Comment by ewg118** [comment]
Okay, a checkbox has been bound to the "Continue" button.
