### ISSUE TITLE
"Unknown" in dpla:SourceResource dcterms:creator

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#6]
The value "unknown" should be stripped from dpla:SourceResource dcterms:creator. Both capitalized and lowercase forms of the word should be stripped. 

The following example may have slipped through because of the trailing comma.

Linfield (currently orplic, will be OrMcL)
http://digitalcommons.linfield.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:lca_rich_photos/
<img width="597" alt="screen shot 2017-02-14 at 11 14 43 am" src="https://cloud.githubusercontent.com/assets/6174191/22944826/dc8ae536-f2a6-11e6-9f87-c825e63d983f.png">

**Comment by ewg118** [comment]
Any dc:creator that contains the word 'unknown' in any case will be suppressed.

**Comment by adehner** [comment]
Would you please resolve this in the test output as well, so our testers can see that these issues are being resolved?
 
http://harvester-dev.orbiscascade.org/test/view?sets=http%3A%2F%2Fdigitalcommons.linfield.edu%2Fdo%2Foai%2F%3Fverb%3DListRecords%26metadataPrefix%3Dsimple-dublin-core%26set%3Dpublication%3Alca_rich_photos%2F&repository=orplic&rights=&output=html&target=both&mode=test

**Comment by ewg118** [comment]
I forgot to pull the changes to the server. Please refresh the page and load again.

**Comment by adehner** [comment]
thanks!
