### ISSUE TITLE
DCMI Type terms showing up in Genre enrichment

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#60]
Yesterday I noticed DCMI Type terms (image, stillimage, etc.) in the list of genre values for enrichment. I hadn't seen this before yesterday. Here's a screenshot showing "image" when enriching genre for cwu's Frederick Krueger's Photographs:

<img width="946" alt="screen shot 2017-04-27 at 1 29 42 pm" src="https://cloud.githubusercontent.com/assets/6174191/25503057/ca2b83ac-2b4d-11e7-9e28-e1d2fb50bf23.png">

@jallibunn

**Comment by ewg118** [comment]
Fixed. Made some alterations to code when introducing the validation on DCMI Type which broke the weeding out of DCMI Types from the Genre list
