### ISSUE TITLE
Validate on presence of standardized rights?

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#61]
We would like this if it's possible and not an arduous update.

@jallibunn

**Comment by ewg118** [comment]
It currently only validates whether dc:rights exists or not, not whether one of the possible values within dc:rights is a rightsstatement.org or creativecommons.org URI. Sometimes a URI is included within a textual statement, so it's difficult to evaluate dc:rights

**Comment by jallibunn** [comment]
In concert with the request to ensure that the second dc:rights free-text statement is present, please:
1. Validate first dc:rights statement for presence and for containing a URI that matches the pattern for either rs.org or CC
2. Validate second dc:rights statement for presence, and containing free text, or free text plus a URL.

**Comment by ewg118** [comment]
Good news. I split the rights validation into two XPath statements, one to look for dc:rights that matches a CC or RS URI, and the other to look for dc:rights that contains neither. Note that other URIs will be validated as acceptable dc:rights "free-text" statements, but not standardized rights statements according to the best practices. An example is the Oregon Digital dc:rights URI for http://opaquenamespace.org/ns/rights/rr-f.

A good test set was from Portland State, which contains no rights statements of either kind: http://pdxscholar.library.pdx.edu/do/oai/?verb=ListRecords&set=publication:usp_grad&metadataPrefix=simple-dublin-core

Initial Validation:
![screenshot from 2017-06-05 18-57-26](https://cloud.githubusercontent.com/assets/563187/26807007/bced5ca4-4a21-11e7-96a9-9600489a9d2d.png)

After selecting a rights URI and entering free text in the text box:
![screenshot from 2017-06-05 18-58-08](https://cloud.githubusercontent.com/assets/563187/26807025/d5c4add6-4a21-11e7-9a97-c0028669112e.png)

**Comment by adehner** [comment]
Awesome! I just tested this with a couple of sets and it works great.
Thanks.
