### ISSUE TITLE
Preview: standardized rights in edm:WebResource edm:rights

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#62]
In the Preview page, please add the standardized rights statement to edm:WebResource edm:rights

sample set:
orpl
http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=58

Here's the screenshot of what I saw:
<img width="833" alt="screen shot 2017-04-27 at 3 20 55 pm" src="https://cloud.githubusercontent.com/assets/6174191/25509144/b32c69fa-2b6b-11e7-870c-f12698c1f007.png">

@jallibunn

**Comment by ewg118** [comment]
I found a glitch in the code that resulted in rightsstatements.org or CC URIs not being parsed as standardized statements from dc:rights when the rights have not been selected in the drop down menu. There will be an issue, though, with textual rights statements. The DPLA MAP implies that the edm:rights in ore:Aggregation and edm:WebResources should be standardized statements (URIs?). So technically, a record is valid if the harvester detects a textual statement, but the edm:rights will not appear in Aggregation or WebResource if they are not a valid CC or RS URI. The DPLA map doesn't require edm:rights at these levels (only recommends), but does require at the dpla:SourceResource. Note there are no upward limits of dc:rights in dpla:SourceResource, but 1 is the max for Aggregation and WebResource, so I don't think we should put textual statements here. There could be multiple textual rights statements in one harvested record, so there's no clear way to choose which one to put into the other data objects.

**Comment by ewg118** [comment]
Is this still active?

**Comment by adehner** [comment]
If CC or RS URIs are reliably parsed and added to edm:rights in Aggregation and WebResource, then this is resolved.

I agree that textual statements should not be added to rights for Aggregation and WebResource, and so far I have not seen any textual rights statements in these data objects.

**Comment by ewg118** [comment]
This should work, but I don't have any way to test it if you don't have an OAI-PMH example set that already has CC or RS URIs in dc:rights. The parsing is here: https://github.com/Orbis-Cascade-Alliance/harvester/blob/master/ui/xslt/serializations/oai/rdf.xsl#L240

**Comment by adehner** [comment]
Here's a set with CC but no free text:
http://oregondigital.org/oai/?verb=ListRecords&set=oregondigital:osu-commencement-programs&metadataPrefix=oai_dc

And here's a set with both RS and free text:
http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=17
