### ISSUE TITLE
Primo preview

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#63]
Today I discovered some glitchiness in the preview of Primo records.
I'm wondering if these are some of the glitches you warned us about. If these are resolvable, please resolve them.

1. dc:format is not displaying in the record preview, but it does display in the validated fields above the record. Please add dc:format to the record preview.

2. Both the free-text and standardized rights statements are previewing in dc:rights. The standardized rights statement should be in the locally qualified field dc:rights.standardized

Screenshot of primo preview for orpl http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=58
<img width="760" alt="screen shot 2017-04-27 at 3 36 34 pm" src="https://cloud.githubusercontent.com/assets/6174191/25509345/0a57e15e-2b6d-11e7-9ed8-c557ccda1179.png">

@jallibunn

**Comment by ewg118** [comment]
Fixed. Had to apply template on format because it's stored in ore:Aggregation, not dpla:SourceResource. Fixed template for rights after switch from dcterms:rights to dc:rights.
