### ISSUE TITLE
"View this set for Primo" returns 0 records

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#64]
After contributing a set for DPLA and Primo, I see the 2 links to view my records:
"View this set for DPLA"
"View this set for Primo"

When I click the link to "View this set for Primo", I see a page with no records. Here's a screenshot of what I saw for orpl http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=58
<img width="1236" alt="screen shot 2017-04-27 at 4 13 19 pm" src="https://cloud.githubusercontent.com/assets/6174191/25509389/732fcafc-2b6d-11e7-8598-9a2e1e321986.png">

@jallibunn

**Comment by ewg118** [comment]
Strange. I'm not seeing it. Maybe another recent change I push fixed it? E.g., http://harvester-dev.orbiscascade.org/results?set=http%3A%2F%2Fdigitalcollections.lclark.edu%2Foai-pmh-repository%2Frequest%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc%26set%3D58&model=primo

**Comment by ewg118** [comment]
I tracked down some other strange error in other sets that were a result of minor XSLT glitches in the way the dpla:SourceResources were getting processed from RDF into OAI-PMH specifically for the test HTML views (unaffected in the Primo OAI-PMH feed)

**Comment by adehner** [comment]
I'm still not seeing any records for Primo when I click the link after Contributing (from the "Thank you for contributing a set" page). I think it's the "amp;" in the link below that's breaking it? 

This is the link: 
http://harvester-dev.orbiscascade.org/results?set=http%3A%2F%2Fdigitalcollections.lclark.edu%2Foai-pmh-repository%2Frequest%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc%26set%3D58amp;model=primo

And this is what I see:
<img width="1233" alt="screen shot 2017-04-28 at 8 43 44 am" src="https://cloud.githubusercontent.com/assets/6174191/25536278/138be5e0-2bef-11e7-8f3d-a53e98d59545.png">

But I DO get records if I click the "View records for Primo" link from this page:
https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/

(here's what the link looks like: http://harvester-dev.orbiscascade.org/results?set=http%3A%2F%2Fdigitalcollections.lclark.edu%2Foai-pmh-repository%2Frequest%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc%26set%3D58&model=primo)

**Comment by ewg118** [comment]
Yes, I spotted a typo on the import page. Had 'amp;' instead of '&amp;' in
the XML
