### ISSUE TITLE
GET API does not accept "limit" parameter

### ISSUE THREAD

**Issue by cwyant-alliance** [Orbis-Cascade-Alliance/harvester#66]
The "limit" parameter for the GET API does not work. We currently use the limit parameter for displaying thumbnails on Archives West finding aids.

**Comment by ewg118** [comment]
I'm a bit confused as to why you believe there is a limit parameter. I never implemented that, and it isn't in the documentation.

**Comment by cwyant-alliance** [comment]
The XSLT for finding aid display includes a "limit" parameter in the call to /get:

<xsl:apply-templates select="document(concat('http://harvester.orbiscascade.org/apis/get?ark=ark:/', //*[local-name()='eadid']/@identifier,	'&amp;format=xml&amp;limit=5'))//res:result"/>

I assume it was put in for a reason. I would prefer to limit the query, if possible, for thumbnail display rather than pulling back the whole collection.

**Comment by ewg118** [comment]
I looked at the code for the API, and there is a limit request parameter that can be passed when you also apply format=json or format=xml (but not when you request for XML or JSON via conneg). I think this may have been made at Keith's request later, but never added into the wiki. It should work:

harvester.orbiscascade.org/apis/get?ark=ark:/80444/xv57799&format=xml&limit=5

**Comment by cwyant-alliance** [comment]
Yes, I can confirm that it works as expected.
