### ISSUE TITLE
Harvester does not return XML for thumbnail display in Archives West

### ISSUE THREAD

**Issue by cwyant-alliance** [Orbis-Cascade-Alliance/harvester#67]
We are using the document() function in our XSLT to grab an XML response from the Harvester (using the GET API) to display preview thumbnails on an Archives West finding aid (example: https://archiveswest.orbiscascade.org/ark:/80444/xv57799)

I can get a properly-formed XML result using curl locally with a "application/sparql-results+xml" Accept header, but I am unsure how this should work with XSLT, or if the GET controller needs to be tweaked to work for this scenario. I should note that this was working fine with the previous version of the Harvester.

**Comment by ewg118** [comment]
Try appending &format=xml to the URL, and you can get the XML document back via REST instead of content negotiation.

**Comment by cwyant-alliance** [comment]
Thanks, that works. I tried it earlier this morning and it was returning an empty XML file. The thumbnails appear to be working now.

**Comment by ewg118** [comment]
I just found that the SPARQL query had an old holdover from the original DPLA model where dcterms:isPartOf was used to link to the finding aid URI instead of dcterms:relation
