### ISSUE TITLE
Return <response>success</response> upon successful ingest

### ISSUE THREAD

**Issue by cwyant-alliance** [Orbis-Cascade-Alliance/harvester#69]
Line 145 in https://github.com/Orbis-Cascade-Alliance/harvester/blob/master/xpl/controllers/ingest.xpl is commented out. Would it be possible to restore the success response upon successful ingest? Right now, the Archives West uploader is simply checking for any response, but it would be nice to have a success/error with descriptive error messages, if possible, from the /ingest endpoint.

**Comment by ewg118** [comment]
The <success> message has been restored.
