### ISSUE TITLE
dc:publisher shouldn't be harvested from source records

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#7]
In the following example, dpla:SourceResource dcterms:publisher is present, but it shouldn't be because the Alliance decided not to harvest dc:publisher from source records.

Marylhurst (ormac)
http://cdm16332.contentdm.oclc.org:80/oai/oai.php?verb=ListRecords&set=p16332coll1&metadataPrefix=oai_dc
<img width="836" alt="screen shot 2017-02-14 at 11 19 12 am" src="https://cloud.githubusercontent.com/assets/6174191/22944988/780b5e32-f2a7-11e6-8acd-392a5d36160d.png">

**Comment by ewg118** [comment]
Okay, dc:publisher is no longer migrated in. The only publisher that will come through is in the OAI-PMH for Primo, and (eventually), it will be the standard repository name from the repository RDF.
