### ISSUE TITLE
Resolving contributions for digital objects linked to finding aids vs. those intended for DPLA/Primo

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#70]
As discussed in call 5/24/17 (Harvester Issues list item 73):
1. Please add an AW target to harvester contribution interface (verbiage for page attached below)
2. Sets that are only in the harvester to be associated with AW finding aids should not be included in the Primo or DPLA endpoints
3. Sets that are only in the harvester to be associated with AW finding aids 
[Harvester_mod3_20170526.pdf](https://github.com/Orbis-Cascade-Alliance/harvester/files/1033332/Harvester_mod3_20170526.pdf)
[Harvester_mod1_20170526.pdf](https://github.com/Orbis-Cascade-Alliance/harvester/files/1033330/Harvester_mod1_20170526.pdf)
[Harvester_mod2_20170526.pdf](https://github.com/Orbis-Cascade-Alliance/harvester/files/1033331/Harvester_mod2_20170526.pdf)
@ewg118

**Comment by jallibunn** [comment]
Could we get an update on progress please?
@ewg118 @orbiscas

**Comment by ewg118** [comment]
I haven't done anything yet.

**Comment by ewg118** [comment]
Okay, I think this is fully functioning now. Please see the email I sent.

**Comment by jallibunn** [comment]
Thank you! I have checked and re-harvested all the sets that were only intended to be linked to AW finding aids (and that clearly didn't meet our requirements for DPLA or Primo), and this seems to be working as expected as far as the harvest. 

And using the Apple Week Publicity Scrapbook from WSU, I've tested the combinations of checkboxes (AW only, AW + DPLA, AW + DPLA + Primo) and everything seems to work as expected.
@ewg118

**Comment by jallibunn** [comment]
HOWEVER, the text on the Contribute Sets doesn't match what I asked you to change it to. Please look at the attached screenshots that show the exact text that needs to be present. 
[Harvester_mod1_20170526.pdf](https://github.com/Orbis-Cascade-Alliance/harvester/files/1050988/Harvester_mod1_20170526.pdf)
[Harvester_mod2_20170526.pdf](https://github.com/Orbis-Cascade-Alliance/harvester/files/1050989/Harvester_mod2_20170526.pdf)

The modifications to the Sets page are acceptable.

**Comment by ewg118** [comment]
You will have to communicate to your partners that their CHOs will still
show up in finding aids when ARKs are found, even if they have only
selected Primo, DPLA, or Both Primo and DPLA.

**Comment by ewg118** [comment]
I have updated the interface.
