### ISSUE TITLE
Language values stripped during harvest

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#72]
In reviewing contributed sets today, I see one set (Maps: Japan - 1843 Mount Fuji) with empty language fields after harvest.

The source OAI contains records with dc:language jap
http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=44

But after harvest the language properties are empty. See screenshots below:

<img width="1197" alt="screen shot 2017-06-01 at 3 26 44 pm" src="https://cloud.githubusercontent.com/assets/6174191/26703871/a5eee778-46e0-11e7-8777-0d987ec4bccf.png">
<img width="1298" alt="screen shot 2017-06-01 at 3 26 12 pm" src="https://cloud.githubusercontent.com/assets/6174191/26703878/abe750d4-46e0-11e7-8f3e-258c5c60eeef.png">

@jallibunn

**Comment by ewg118** [comment]
'jpn' is the ISO 3 letter code. I discovered a glitch where non-matches to the ISO code still resulted in a blank language value. This glitch has been fixed and these records will no longer have a language value.
