### ISSUE TITLE
dcterms:extent in Preview before contribution

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#75]
In testing this morning, I see that dcterms:extent is still present when previewing records before contributing a set. We agreed to only harvest mime types from dc:format and I haven't seen dcterms:extent in harvested sets. But it's still appearing when previewing records, which is confusing to Alliance users.

Please remove dcterms:extent from the preview metadata.

Here is a screenshot from my test this morning:
<img width="1047" alt="screen shot 2017-06-02 at 10 07 01 am" src="https://cloud.githubusercontent.com/assets/6174191/26736664/ef24d876-477b-11e7-9684-b3dd215c9891.png">

@jallibunn

**Comment by ewg118** [comment]
I can disable this, but the dcterms:extent is not a dc:extent from OAI-PMH.
Is the semantic definition of an extent parsed out of dc:format.

**Comment by adehner** [comment]
Yes, I remember that the dcterms:extent is parsed from dc:format. It's a clever solution for dealing with the digital vs. original format dilemma! But for the time being, the Alliance has decided to keep dc:format harvesting simple, by only harvesting mime types. So please disable dcterms:extent in preview and in harvest.

**Comment by ewg118** [comment]
Okay, I commented out the extent parsing, but it can be re-enabled at some point in the future, if you choose.
