### ISSUE TITLE
Contributed sets not displaying for Alliance members

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#77]
Yesterday Linfield contributed 4 sets. But when the Linfield contributor visits the [Harvester's back-end landing page](https://harvester.orbiscascade.org:8443/orbeon/harvester/admin/), she does not see any sets listed. Instead she sees this:

![harvesteradminscreen](https://cloud.githubusercontent.com/assets/6174191/26793064/6e1404f2-49d1-11e7-94f8-b6cf60468e9b.jpg)

@jallibunn

**Comment by adehner** [comment]
Related question: 
When this issue was reported to us, I suggested that she click the "refresh repository metadata" button. But learned afterwards that Alliance members can't see this link. When would we want to "refresh repository metadata" and/or what does clicking this link do?

**Comment by ewg118** [comment]
This isn't related to repository metadata per se, and Alliance members shouldn't have authority to reindex these data.

I found that the SPARQL query for generating the set list wasn't updated to use one of two possible URIs, one for AW and the other the internal (e.g., http://harvester.orbiscascade.org/agency/ormcl) when a repository is not an AW member. This is fixed. Linfield should now see their sets.
