### ISSUE TITLE
Test harvester is not generating output

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#8]
When submitting an OAI set in the [test harvester interface](http://harvester-dev.orbiscascade.org/test), a blank output page displays instead of HTML or RDF output. 

<img width="1223" alt="screen shot 2017-02-20 at 9 38 01 am" src="https://cloud.githubusercontent.com/assets/6174191/23136187/59f14f30-f750-11e6-9161-e62089ed2c38.png">

Sample output page:
http://harvester-dev.orbiscascade.org/test/view?sets=http%3A%2F%2Fdigitalcommons.linfield.edu%2Fdo%2Foai%2F%3Fverb%3DListRecords%26set%3Dpublication%3Adory_audio_all%26metadataPrefix%3Dsimple-dublin-core&repository=ormcl&rights=&output=html&target=both&mode=test

**Comment by ewg118** [comment]
Fixed RDF/HTML5 serializations in the XML Pipeline for the test interface
