### ISSUE TITLE
Thumbnail URL for Omeka pdfs

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#80]
All Omeka thumbnail images are image/jpg. And the file path for thumbnails of Omeka pdfs follows a reliable pattern:
pdf = http://digitalcollections.lclark.edu/files/original/e758c06d94c8c245f97cb57b7148e4fc.pdf
thumb = http://digitalcollections.lclark.edu/files/thumbnails/e758c06d94c8c245f97cb57b7148e4fc.jpg

Today Lewis & Clark contributed a set (http://harvester.orbiscascade.org/results?set=http%3A%2F%2Fdigitalcollections.lclark.edu%2Foai-pmh-repository%2Frequest%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc%26set%3D47&model=primo) and the thumbnail URL in dc:hasVersion (for Primo) has a .pdf extension. The webResource for DPLA might as well.

Please update the file extension for thumbnails of Omeka pdfs to be .jpg 

@jallibunn

**Comment by ewg118** [comment]
The XSLT was simply looking to replace 'tif' with 'jpg', but I have tightened up the expression to replace any file extension with 'jpg'. Note that I have no idea what happens in Omeka with sound or video files, and problems may occur (difficult to anticipate) if someone uploads a file that doesn't have an extension.

**Comment by adehner** [comment]
This is a good point, and one we should monitor. I'll see if I can find a
couple of A/V examples to see what happens.

Anneliese
