### ISSUE TITLE
Missing language

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#82]
For the set from Lewis & Clark on Mt Fuji, http://digitalcollections.lclark.edu/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=44, the original metadata has this for language: 

<dc:language>jap</dc:language>

Both the DPLA and Primo views have no value for language. According to the specs, the output should be the ISO 639-2 code.

@orbiscas @ewg118

**Comment by ewg118** [comment]
This was already opened as an issue and closed. 'jpn' is the ISO code
