### ISSUE TITLE
AW linked OAI sets and harvester

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#83]
Following up on the long email thread with the title "Question"...and Ethan's statement: 
"Curtis will have to make some changes to the code in AW to ensure that the ingest sequence isn't initiated after the check API responds with a warning message."

@cwyant: Curtis, how soon could you make this change?

Once Curtis has and we are satisfied by the functionality, Anneliese and I feel strongly that we need to keep the submission process separate for AW and the harvester; otherwise it's extremely confusing to users. 

So, let's plan for this:

1. Ethan: Please remove the Archives West references on the harvester contribution page as marked in the attachments. 
<img width="1280" alt="aw text 2" src="https://user-images.githubusercontent.com/25933545/26996993-9c7fa728-4d33-11e7-8cb4-35da4c7eff6a.png">
<img width="1280" alt="aw text 1" src="https://user-images.githubusercontent.com/25933545/26996994-9c7fb34e-4d33-11e7-9d62-a3a26be4cccc.png">

2. Anneliese: Once Curtis and Ethan have done the above, you can finish the documentation revisions and have Elizabeth post them. 

@orbiscas @ewg118

**Comment by cwyant-alliance** [comment]
I'm waiting for Ethan to update the Check API, as discussed in our previous email thread, the return a message if the set exists on the Harvester in the AW and DPLA/Primo targets. As far as I know, this change has not been implemented.

Once it has been updated, I can update AW pretty quickly since it already performs a check as part of the upload sequence.

**Comment by ewg118** [comment]
I removed the AW options. Still working on updating the check API

**Comment by ewg118** [comment]
For reference, here's a SPARQL query that evaluates whether a set has been designated for Primo or DPLA: https://gist.github.com/ewg118/2961831c21c82ba0789cc75288761643
