### ISSUE TITLE
fixes for VOID file

### ISSUE THREAD

**Issue by VladimirAlexiev** [Orbis-Cascade-Alliance/harvester#87]
http://harvester.orbiscascade.org/void.ttl
`void:sparqlEndpoint "http://harvester.orbiscascade.org/query";`

This line is doubly wrong:
- its a string not URL
- the correct URL is http://harvester.orbiscascade.org/query

Also, that's a very minimal VOID. Can you add the sub-datasets (PMH sets), the number of void:entities in each one, and total and per-dataset number of triples?

**Comment by ewg118** [comment]
I updated the SPARQL query URL, but I'm not going to make the other changes. This endpoint exists for DPLA.
