### ISSUE TITLE
Order of geographic coordinates in separate properties: Latitude first, then longitude

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#9]
When geographic coordinates are present in separate dc:coverage properties, the harvester is mapping the first dc:coverage to longitude and the next dc:coverage to latitude.

sample OAI-PMH:
http://digitalcommons.linfield.edu/do/oai/?verb=ListRecords&set=publication:owha_eyrie_photos&metadataPrefix=simple-dublin-core

<img width="703" alt="screen shot 2017-02-21 at 11 06 14 am" src="https://cloud.githubusercontent.com/assets/6174191/23180298/d473435a-f825-11e6-9b7d-e5bba1f697d9.png">

The [Alliance Dublin Core Best Practices](https://www.orbiscascade.org/dublin-core-best-practices/) require that they are ordered as latitude first, then longitude. When geographic coordinates are present in separate dc:coverage properties, please treat the first property as latitude and the next as longitude.

**Comment by ewg118** [comment]
However, in the Digital Commons instance for Western Washington University, the order is longitude then latitude: http://cedar.wwu.edu/do/oai/?verb=ListRecords&set=publication:klipsun_magazine&metadataPrefix=simple-dublin-core

The danger here is that there is no clear cut way to validate these fields, so if we process lat then long, the point will end up somewhere very far away, but still be a valid geographic coordinate. If WWU is unable to change the script for exporting OAI-PMH, I would consider not allowing latitude and longitude values to be in separate fields at all.

**Comment by adehner** [comment]
It is true that they have ordered the fields as longitude first. But they will need to modify this to be compliant. 

I've checked with Digital Commons and surveyed the data of Alliance repositories outputting coordinates in separate properties. The Digital Commons default order is lat first, then long. And most Alliance libraries follow this pattern. Western Washington is the outlier. I spoke with a Digital Commons consultant a couple of weeks ago, and she confirmed that swapping the order in which fields are output is no problem at all.

It would be ideal to output these values in one property. However Digital Commons uses a 3rd party app to enable browsing via a Google map. This geographic browse functionality relies on the presence of coordinates in separate fields, but their order doesn't affect this functionality. The google maps feature is why we're seeing so many coordinates in separate properties.

**Comment by ewg118** [comment]
Okay. I'll switch the processing order back to lat, long. Hopefully WWU can get it sorted out before the system goes into production.

**Comment by adehner** [comment]
Thanks Ethan. I'll get in touch with them to let them know.

**Comment by ewg118** [comment]
I switched the order back and ingested this set. You can see that the coordinate are correct in http://harvester-dev.orbiscascade.org/record/a827c1e7f4e6ca341883c2a656ad86c1. I have not re-ingested the WWU set, so technically their lat and long are still correct.
