### ISSUE TITLE
Re-submitted sets with rights statements applied in harvester retained earlier versions

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#91]
Looking at sets of "The Crescent" submitted by George Fox University: GFU had submitted this as a single set earlier with a single copyright statement. That statement was only accurate for the post-1923 items, so I asked them to re-submit with accurate statements. They divided the single set into multiple ones and re-submitted, applying the standardized and free-text rights statements in the harvester. The harvester retained both the information submitted the first time and the second time; see, for example, The Crescent, 1895-1899.
@cwyant-alliance

**Comment by ewg118** [comment]
This is an instance where they need to delete the old set from the admin panel because there are two new sets with different URIs.

**Comment by jallibunn** [comment]
Great, I will communicate that to them. 

@cwyant-alliance
