### ISSUE TITLE
19uu dates start/end for Primo

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#92]
An item (http://cdm16085.contentdm.oclc.org/cdm/ref/collection/p15013coll4/id/207) in a set contributed by SOU has a date of 19uu. The Primo version does not have the dc:date.start and dc:date.end properties, which should be 1900 and 1999 respectively.
@cwyant-alliance

**Comment by ewg118** [comment]
Duplicate of #85

**Comment by jallibunn** [comment]
So it is. And now you have more than one example to text a fix!
@cwyant-alliance
