### ISSUE TITLE
OSU OAI sets

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#95]
Picking this issue up from October in hopes that we can resolve it. 

Set in question: http://oregondigital.org/oai/?verb=ListRecords&set=oregondigital:textile-and-apparel&metadataPrefix=oai_dc from Oregon State

They were removing donor and designer names and re-submitted it several times (see email thread). When they tried again on October 6, they got the error message Alert: Unable to parse the OAI-PMH response for ListSets. We found that they had recently changed Oregon Digital to https from http. You advised that the solution was to re-set the OD OAI-PMH response so that the <request> verb is https://oregondigital.org/oai rather than http://oregondigital.org/oai.

They made this change on October 12, tried re-submitting on October 13, and got the same error message. 

@cwyant-alliance

**Comment by ewg118** [comment]
The set URL has to be https:// . Everything must be https

    curl -I http://oregondigital.org/oai/?verb=ListSets
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.10.2
    Date: Fri, 17 Nov 2017 18:55:45 GMT
    Content-Type: text/html
    Content-Length: 185
    Connection: keep-alive
    Location: https://oregondigital.org/oai/?verb=ListSets

**Comment by jallibunn** [comment]
Thank you, I will pass that along to them.
