### ISSUE TITLE
HTTPS in Bepress OAI

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#96]
All or some of our contributing institutions that use BePress now use https rather than http. 

Do I give them the same advice we gave to OSU (re-set the OD OAI-PMH response so that the <request> verb is https://***/oai rather than http://***/oai.)? 

Please advise.

**Comment by ewg118** [comment]
Yes, and they should delete everything they've already published and re-publish.

**Comment by jallibunn** [comment]
Thanks! To clarify: The deletion step is required before re-submitting? 
@cwyant-alliance

**Comment by ewg118** [comment]
Yes, be sure to delete first before resubmitting. The CHOs are bound together by the URI of the set itself (dcterms:isPartOf). It'll be a mess if you don't delete existing sets first, as you may have CHOs linked to two sets (one http and one https) or you'll have two identical sets of CHOs, one with http URIs and one with https. A URI is unique, regardless of whether the 's' is there or not. LOD systems don't natively reconcile this difference.
