### ISSUE TITLE
Harvester contribution error: Reed

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#99]
@ewg118 
Reed is unable to contribute a new set to the harvester. Here is the message from them:

I'm submitting my promised digital objects before the end of June, and ran into a harvester error:
"Unable to parse the OAI-PMH response for ListSets"

Here's the set I'm submitting:
https://rdc.reed.edu/oai?verb=ListRecords&set=reedhisttxt&metadataPrefix=oai_dc

And I am able to put in the following into a browser, and get what seems normal data back:
https://rdc.reed.edu/oai?verb=ListSets

**Comment by jallibunn** [comment]
@ewg118 
I've compared this set to the two they already have in the harvester, and am not seeing any difference in them at a high level. This is probably some rather simple thing that I'm just missing. 

The only thing I see is that in the DAM and IR inventory that you have been using for the registry, they list their DAM as http, and it's now https.

**Comment by ewg118** [comment]
curl reports the following error, which may be affecting the harvester as well. This is an http/https issue. I tested Williamette's set (also https), and it functions.


    curl "https://rdc.reed.edu/oai?verb=ListRecords&set=reedhisttxt&metadataPrefix=oai_dc"
    curl: (60) SSL certificate problem: unable to get local issuer certificate
    More details here: https://curl.haxx.se/docs/sslcerts.html

    curl failed to verify the legitimacy of the server and therefore could not
    establish a secure connection to it. To learn more about this situation and
    how to fix it, please visit the web page mentioned above.

**Comment by jallibunn** [comment]
@ewg118 OK, I will pass the message on the legitimacy of the server to Reed and see what they say. 

On the http/https issue: Does Reed need to do anything on that, or is that something to address in the harvester?

**Comment by jallibunn** [comment]
Reed is dealing with the server issue, and has updated their DAM/IR registry entry.
